# Generated by Django 4.2.13 on 2024-06-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dataNascimento', models.DateField()),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.cidade')),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['palavra'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('dataPublicacao', models.DateField()),
                ('conferencia', models.CharField(max_length=150)),
                ('abstract', models.TextField()),
                ('url', models.URLField()),
                ('publicado_em', models.CharField(choices=[('J', 'Journal'), ('C', 'Conferência'), ('L', 'Livro')], default='J', max_length=10)),
                ('abrangencia', models.CharField(choices=[('INT', 'Internacional'), ('NAC', 'Nacional'), ('REG', 'Regional'), ('LOC', 'Local')], max_length=3)),
                ('tipo', models.CharField(choices=[('RESUM', 'Resumo Expandido'), ('FULLP', 'Full Paper'), ('LIVRO', 'Livro'), ('CAPLI', 'Capítulo de Livro'), ('TESES', 'Tese de Doutorado'), ('DISSE', 'Dissertação de Mestrado'), ('RELAT', 'Relatório Técnico'), ('MONOG', 'Trabalho de Conclusão de Curso'), ('OUTRO', 'Outro')], max_length=5)),
                ('autor', models.ManyToManyField(to='fabricaNode.autor')),
                ('editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.editora')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.area')),
            ],
            options={
                'verbose_name': 'Subárea',
                'verbose_name_plural': 'Subáreas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Publicacao_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.keyword')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.publicacao')),
            ],
            options={
                'verbose_name': 'Publicação Keyword',
                'verbose_name_plural': 'Publicações Keywords',
                'ordering': ['publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.pais')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['sigla'],
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.estado'),
        ),
        migrations.AddField(
            model_name='autor',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.cidade'),
        ),
        migrations.AddField(
            model_name='autor',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.subarea'),
        ),
    ]
