# Generated by Django 4.2.14 on 2024-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
