# Generated by Django 5.0.4 on 2024-06-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNode', '0002_area_subarea_autor_subarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='editora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fabricaNode.editora'),
        ),
    ]
