# Generated by Django 4.2.14 on 2024-08-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabricaNode", "0002_alter_area_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="dataNascimento",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="dataPublicacao",
            field=models.IntegerField(),
        ),
    ]
