# Generated by Django 4.2.14 on 2026-08-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fabricaNode", "0003_alter_autor_datanascimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="cor",
            field=models.CharField(default="#267A7A", max_length=7),
        ),
        migrations.AddField(
            model_name="autor",
            name="academia_edu_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="favoritos",
            field=models.ManyToManyField(
                blank=True,
                related_name="autores_favoritos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="google_scholar_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="lattes_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="orcid_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="researchgate_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="autor_perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, related_name="publicacoes", to="fabricaNode.area"
            ),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="favoritos",
            field=models.ManyToManyField(
                blank=True,
                related_name="publicacoes_favoritas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="abrangencia",
            field=models.CharField(
                choices=[
                    ("INT", "Internacional"),
                    ("NAC", "Nacional"),
                    ("REG", "Regional"),
                    ("LOC", "Local"),
                ],
                default="NAC",
                max_length=3,
            ),
        ),
    ]
