# Generated by Django 4.2.14 on 2026-08-26 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fabricaNode", "0004_area_cor_autor_academia_edu_id_autor_favoritos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="cidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="fabricaNode.cidade",
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="dataNascimento",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autor",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="autor_perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
