# Generated by Django 4.2.14 on 2026-08-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabricaNode", "0005_alter_autor_cidade_alter_autor_datanascimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="biografia",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="autor",
            name="foto_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="autor",
            name="github",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="autor",
            name="instagram",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="autor",
            name="linkedin",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="autor",
            name="portal_member_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
