# Generated by Django 4.2.14 on 2026-08-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabricaNode", "0006_autor_biografia_autor_foto_url_autor_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="openalex_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
