# Generated by Django 5.0.4 on 2024-06-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricaNode', '0003_alter_publicacao_editora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subarea',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
