from .area import AreaSerializer
from .autor import AutorSerializer
from .cidade import CidadeSerializer
from .editora import EditoraSerializer
from .estado import EstadoSerializer
from .keyword import KeywordSerializer
from .pais import PaisSerializer
from .publicacao_keyword import Publicacao_keywordSerializer
from .publicacao import PublicacaoSerializer