# Generated by Django 4.2.14 on 2026-08-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="passage_id",
        ),
    ]
