from .area import AreaViewSet
from .autor import AutorViewSet
from .cidade import CidadeViewSet
from .editora import EditoraViewSet
from .estado import EstadoViewSet
from .keyword import KeywordViewSet
from .pais import PaisViewSet
from .publicacao_keyword import Publicacao_keywordViewSet
from .publicacao import PublicacaoViewSet
from .subarea import SubareaViewSet